
package service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T19:58:16.252+08:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "LoginException", targetNamespace = "http://service/")
public class LoginException extends Exception {
    
    private service.FaultBean loginException;

    public LoginException() {
        super();
    }
    
    public LoginException(String message) {
        super(message);
    }
    
    public LoginException(String message, Throwable cause) {
        super(message, cause);
    }

    public LoginException(String message, service.FaultBean loginException) {
        super(message);
        this.loginException = loginException;
    }

    public LoginException(String message, service.FaultBean loginException, Throwable cause) {
        super(message, cause);
        this.loginException = loginException;
    }

    public service.FaultBean getFaultInfo() {
        return this.loginException;
    }
}
