
package edu.nju.soa.schema.tns;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NotFoundFault", targetNamespace = "http://jw.nju.edu.cn/schema")
public class IdNotFoundException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NotFoundType faultInfo;

    public IdNotFoundException(NotFoundReasonType reasonType, String notFoundId, String massage) {
        super(massage);
        faultInfo = new NotFoundType(reasonType,notFoundId);
    }

    /**
     *
     * @param faultInfo
     * @param message
     */
    public IdNotFoundException(String message, NotFoundType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IdNotFoundException(String message, NotFoundType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: cn.edu.nju.jw.schema.NotFoundType
     */
    public NotFoundType getFaultInfo() {
        return faultInfo;
    }

}
