<?xml version="1.0" encoding="utf-8" ?>
<description
    xmlns="http://www.w3.org/ns/wsdl"
    targetNamespace= "http://jw.nju.edu.cn/wsdl"
    xmlns:ttns= "http://jw.nju.edu.cn/wsdl"
    xmlns:wsoap= "http://www.w3.org/ns/wsdl/soap"
    xmlns:soap="http://www.w3.org/2003/05/soap-envelope"
    xmlns:wsdlx="http://www.w3.org/2006/01/wsdl-extensions">

    <documentation>
        This document describes the StudentVerification Web service.
    </documentation>

    <types>
      <xs:schema
          xmlns="http://www.w3.org/2001/XMLSchema"
          targetNamespace="http://jw.nju.edu.cn/wsdl"
          xmlns:vxs="http://jw.nju.edu.cn/wsdl">

        <xs:import namespace="http://jw.nju.edu.cn/schema" schemaLocation="Student.xsd"></xs:import>
        <xs:import namespace="http://jw.nju.edu.cn/schema" schemaLocation="Wrong.xsd"></xs:import>
        <xs:import namespace="http://jw.nju.edu.cn/schema" schemaLocation="Verification.xsd"></xs:import>

      </xs:schema>
    </types>

    <interface  name = "studentVerificationInterface">
      <fault name = "invalidDataFault"
                element = "vxs:错误信息"/>

      <operation name="verify"
                pattern="http://www.w3.org/ns/wsdl/in-out"
                style="http://www.w3.org/ns/wsdl/style/iri"
                wsdlx:safe = "true">
            <input messageLabel="In"
                  element="vxs:学号" />
            <output messageLabel="Out"
                  element="vxs:验证信息" />
            <outfault ref="ttns:invalidDataFault" messageLabel="Out"/>
        </operation>
    </interface>

    <binding name="studentVerificationSOAPBinding"
              interface="ttns:studentVerificationInterface"
              type="http://www.w3.org/ns/wsdl/soap"
              wsoap:protocol="http://www.w3.org/2003/05/soap/bindings/HTTP/">

        <fault ref="ttns:invalidDataFault"
          wsoap:code="soap:Sender"/>

        <operation ref="ttns:verify"
          wsoap:mep="http://www.w3.org/2003/05/soap/mep/soap-response"/>

    </binding>

    <service name="studentVerificationService"
           interface="ttns:studentVerificationInterface">

       <endpoint name="studentVerificationEndpoint"
                   binding="ttns:studentVerificationSOAPBinding"
                   address ="http://localhost:8080/studentVerification"/>
    </service>

</description>
