
package cn.edu.nju.jw.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T20:00:54.094+08:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "分数错误", targetNamespace = "http://jw.nju.edu.cn/schema")
public class InvalidScore extends Exception {
    
    private java.lang.String 分数错误;

    public InvalidScore() {
        super();
    }
    
    public InvalidScore(String message) {
        super(message);
    }
    
    public InvalidScore(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidScore(String message, java.lang.String 分数错误) {
        super(message);
        this.分数错误 = 分数错误;
    }

    public InvalidScore(String message, java.lang.String 分数错误, Throwable cause) {
        super(message, cause);
        this.分数错误 = 分数错误;
    }

    public java.lang.String getFaultInfo() {
        return this.分数错误;
    }
}
