
package cn.edu.nju.jw.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T20:00:54.042+08:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "课程编号错误", targetNamespace = "http://jw.nju.edu.cn/schema")
public class InvalidCourseId extends Exception {
    
    private java.lang.String 课程编号错误;

    public InvalidCourseId() {
        super();
    }
    
    public InvalidCourseId(String message) {
        super(message);
    }
    
    public InvalidCourseId(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCourseId(String message, java.lang.String 课程编号错误) {
        super(message);
        this.课程编号错误 = 课程编号错误;
    }

    public InvalidCourseId(String message, java.lang.String 课程编号错误, Throwable cause) {
        super(message, cause);
        this.课程编号错误 = 课程编号错误;
    }

    public java.lang.String getFaultInfo() {
        return this.课程编号错误;
    }
}
