package cn.edu.nju.jw.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-26T20:00:54.107+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://jw.nju.edu.cn/wsdl", name = "ScoreManageService")
@XmlSeeAlso({cn.edu.nju.schema.ObjectFactory.class, cn.edu.nju.jw.schema.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ScoreManageService {

    @WebMethod
    @WebResult(name = "课程成绩列表", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 课程成绩列表类型 deleteGrade(
        @WebParam(partName = "parameters", name = "学号课程号", targetNamespace = "http://jw.nju.edu.cn/schema")
        学号课程号类型 parameters
    ) throws InvalidCourseId, InvalidStudentId;

    @WebMethod
    @WebResult(name = "课程成绩列表", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 课程成绩列表类型 queryGrade(
        @WebParam(partName = "parameters", name = "学号", targetNamespace = "http://jw.nju.edu.cn/schema")
        java.lang.String parameters
    ) throws InvalidStudentId;

    @WebMethod
    @WebResult(name = "课程成绩列表", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 课程成绩列表类型 modifyGrade(
        @WebParam(partName = "parameters", name = "课程成绩", targetNamespace = "http://jw.nju.edu.cn/schema")
        课程成绩类型 parameters
    ) throws InvalidCourseId, InvalidStudentId, InvalidScore;

    @WebMethod
    @WebResult(name = "课程成绩列表", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 课程成绩列表类型 sortGrade(
        @WebParam(partName = "parameters", name = "排序", targetNamespace = "http://jw.nju.edu.cn/schema")
        排序类型 parameters
    ) throws InvalidCourseId, InvalidStudentId;

    @WebMethod
    public void addGrade(
        @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "课程成绩列表", targetNamespace = "http://jw.nju.edu.cn/schema")
        javax.xml.ws.Holder<课程成绩列表类型> parameters
    ) throws InvalidCourseId, InvalidStudentId, InvalidScore;
}
