package cn.edu.nju.jw.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-28T20:20:51.743+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "StudentInfoServiceImplService", 
                  wsdlLocation = "http://106.15.91.25:8080/grade/cxf/studentInfoService?wsdl",
                  targetNamespace = "http://jw.nju.edu.cn/wsdl") 
public class StudentInfoServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://jw.nju.edu.cn/wsdl", "StudentInfoServiceImplService");
    public final static QName StudentInfoServicePort = new QName("http://jw.nju.edu.cn/wsdl", "StudentInfoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://106.15.91.25:8080/grade/cxf/studentInfoService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentInfoServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://106.15.91.25:8080/grade/cxf/studentInfoService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentInfoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentInfoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentInfoServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public StudentInfoServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentInfoServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentInfoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns StudentInfoService
     */
    @WebEndpoint(name = "StudentInfoServicePort")
    public StudentInfoService getStudentInfoServicePort() {
        return super.getPort(StudentInfoServicePort, StudentInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentInfoService
     */
    @WebEndpoint(name = "StudentInfoServicePort")
    public StudentInfoService getStudentInfoServicePort(WebServiceFeature... features) {
        return super.getPort(StudentInfoServicePort, StudentInfoService.class, features);
    }

}
