package cn.edu.nju.jw.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-28T20:20:51.712+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://jw.nju.edu.cn/wsdl", name = "StudentInfoService")
@XmlSeeAlso({cn.edu.nju.schema.ObjectFactory.class, cn.edu.nju.jw.schema.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StudentInfoService {

    @WebMethod(action = "http://localhost:8080/cxf/studentInfoService/addInfoRequest")
    @Action(input = "http://localhost:8080/cxf/studentInfoService/addInfoRequest", output = "http://localhost:8080/cxf/studentInfoService/addInfoResponse", fault = {@FaultAction(className = DataFormatError.class, value = "http://jw.nju.edu.cn/wsdl/StudentInfoService/addInfo/Fault/DataFormatError")})
    public void addInfo(
        @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "学生", targetNamespace = "http://jw.nju.edu.cn/schema")
        javax.xml.ws.Holder<学生信息> parameters
    ) throws DataFormatError;

    @WebMethod
    @WebResult(name = "学生", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 学生信息 deleteInfo(
        @WebParam(partName = "parameters", name = "学号类型", targetNamespace = "http://jw.nju.edu.cn/schema")
        cn.edu.nju.schema.学号类型 parameters
    ) throws InvalidStudentId;

    @WebMethod(action = "http://localhost:8080/cxf/studentInfoService/modifyInfoRequest")
    @Action(input = "http://localhost:8080/cxf/studentInfoService/modifyInfoRequest", output = "http://localhost:8080/cxf/studentInfoService/modifyInfoResponse", fault = {@FaultAction(className = DataFormatError.class, value = "http://jw.nju.edu.cn/wsdl/StudentInfoService/modifyInfo/Fault/DataFormatError")})
    public void modifyInfo(
        @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "学生", targetNamespace = "http://jw.nju.edu.cn/schema")
        javax.xml.ws.Holder<学生信息> parameters
    ) throws DataFormatError;

    @WebMethod
    @WebResult(name = "学生", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 学生信息 queryInfo(
        @WebParam(partName = "parameters", name = "学号", targetNamespace = "http://jw.nju.edu.cn/schema")
        java.lang.String parameters
    ) throws InvalidStudentId;
}
