<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<description 
	xmlns="http://www.w3.org/ns/wsdl"
	targetNamespace="http://jw.nju.edu.cn/fault/wsdl"
	xmlns:fault="http://jw.nju.edu.cn/fault/wsdl"
	xmlns:wsoap="http://www.w3.org/ns/wsdl/soap"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	
	
	<!-- 类型定义 -->
	<types>
	
		<xs:element name="InvalidDataFault" type="xsd:string" />
		
	</types>
	
	
	<!-- 负责定义错误 -->
	<interface name="scoreFaultInterface">
		<fault name="idNotFindFault" element="fault:InvalidDataFault">
			<documentation>学号不存在错误</documentation>
		</fault>
		<fault name="studentIdFault" element="fault:InvalidDataFault">
			<documentation>修改成绩时，输入的学号未找到</documentation>
		</fault>
		<fault name="courseIdFault" element="fault:InvalidDataFault">
			<documentation>修改改成绩时，选择的课程未找到</documentation>
		</fault>
		<fault name="scoreTypeFault" element="fault:InvalidDataFault">
			<documentation>修改成绩时成绩类型错误</documentation>
		</fault>
		<fault name="scoreModifyFault" element="fault:InvalidDataFault">
			<documentation>修改成绩时分数格式错误</documentation>
		</fault>
	</interface>


</description>